---
title: "Amazon Camera Reviews "
subtitle: "Nathan's Data Science Portfolio"
output:
  html_document:
    df_print: paged
---

## Abstract

### 1. Discovery and Data Preparation

This first deliverable starts to look at reviews provided by Amazon and what questions should be asked to get the most from the dataset. [First Deliverable](https://htmlpreview.github.com/?https://github.com/Nathan-Lovell/DataScience-Nathan-Lovell/master/deliverable1.html)

### 2. Model Planning and Building

This second deliverable looks at adding a new data set to suplement the one discovered in deliverable 1. It also starts looking at models by testing out an initial model and plans for moving forwards. [Second Deliverable](https://htmlpreview.github.com/?https://github.com/Nathan-Lovell/DataScience-Nathan-Lovell/master/deliverable2.html)

### 3. Results and Operationalization

This third deliverable pulls all of the other deliverables together and looks into how this data can be usefull. This deliverable also has a section on how this work can be ethically operationalized for any businesses that has reviews impact their sales. [Third Deliverable](https://htmlpreview.github.com/?https://github.com/Nathan-Lovell/DataScience-Nathan-Lovell/master/deliverable3.html)

